name: Python tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libpq-dev
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        bash shell/run_flake.sh
    - name: Django tests
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
      run: |
        python manage.py migrate
        python manage.py test
